config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 250}
  enum status: { "未着手": 0, "着手中": 1, "完了": 2 }
  enum priority: { "低": 0, "中": 1, "高": 2 }
  scope :search_title, -> (search){ where('title like ?', "%#{search}%") if search.present? }
  scope :search_status, -> (status){ where(status: status) if status.present? }
  scope :search_label, -> (label){ joins(:labels).where('labels.id = ?', label) if label.present? }
  paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :admin_cannot_delete
  before_update :admin_cannot_update

  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, length: {maximum: 255},
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }

  private

  def admin_cannot_update
    if User.where(admin: true).count == 1 && self.admin_change == [true, false]
      errors.add(:base, '管理者は必ず一人必要です')
      throw :abort
    end
  end

  def admin_cannot_delete
    if User.where(admin: true).count == 1 && self.admin == true
      errors.add(:base, '管理者は必ず一人必要です')
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  before_action :set_user, only: %i[ show edit destroy update ]

  def index
    @users = User.all.includes(:tasks)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'ユーザーを作成しました'
      redirect_to admin_users_path
    else
      flash[:notice] = '作成できませんでした'
      render :new
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def destroy
    if @user.destroy
      flash[:notice] = '削除しました'
      redirect_to admin_users_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      redirect_to admin_users_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'ユーザー情報を更新しました'
      redirect_to admin_users_path
    else
      flash.now[:error] = @user.errors.full_messages.join(', ')
      render :edit
    end
  end

  def edit
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :admin)
  end

  def admin_user
    unless current_user && current_user.admin?
      flash[:danger] = '管理者以外アクセスできません'
      redirect_to tasks_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    unless current_user
      flash[:danger] = 'ログインしてください'
      redirect_to new_session_path
    end
  end

  def not_create_user
    redirect_to tasks_path if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :show]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      if user.admin?
        flash[:notice] = '管理者としてログインしました'
        redirect_to admin_users_path
      else
        flash[:notice] = 'ログインしました'
        redirect_to user_path(user.id)
      end
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

    def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit destroy update ]

  def index
    @tasks = current_user.tasks.page(params[:page]).per(5)
    if params[:sort_expired]
      @tasks = @tasks.all.order(expired_at: "DESC").page(params[:page])
    elsif params[:sort_priority]
      @tasks = @tasks.all.order(priority: "DESC").page(params[:page])
    elsif params[:search].present? || params[:status].present?
      @tasks = @tasks.search_title(params[:search]).search_status(params[:status]).page(params[:page])
    elsif params[:label_ids].present?
      @tasks = @tasks.search_label(params[:label_ids]).page(params[:page])
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'タスクを編集しました'
      redirect_to task_path
    else
      render :edit
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:notice] = 'タスクを作成しました'
      redirect_to tasks_path
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = 'タスクを削除しました'
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :expired_at, :status, :priority,
    { label_ids: [] })
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[ new create ]
  before_action :not_create_user, only: %i[ new create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = '新規登録しました'
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if current_user.admin? || @user == current_user
    else
      flash[:notice] = '自分以外のマイページにはアクセスできません'
      redirect_to tasks_path
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def admin?
    current_user == User.find_by(id: session[:admin])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザー情報更新画面</h1>
<%= form_with(model: @user, url: admin_user_path(@user), local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br>
  <%= f.label :email %>
  <%= f.email_field :email %>
<br>
  <%= f.label :password %>
  <%= f.password_field :password %>
<br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
<br>
<% if @user.admin != true %>
  <%= f.radio_button :admin, :true %>
  <%= f.label :admin, "管理者権限を付与する" %>
<% else %>
  <%= f.radio_button :admin, :false %>
  <%= f.label :admin, "権限を削除する" %>
<% end %>
<br>
  <%= f.submit "更新" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>管理者画面</h1>
<%= link_to 'ユーザー新規作成', new_admin_user_path, class: 'btn btn-light btn-sm' %>
<br>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>投稿数</th>
    </tr>
  </thead>
  <br>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th><%= user.id %></th>
        <th><%= user.name %></th>
        <th><%= user.tasks.count %>件</th>
        <th>
          <%= link_to '詳細', user_path(user) %>
          <%= link_to '編集', edit_admin_user_path(user) %>
          <%= link_to '削除', admin_user_path(user), method: :delete, data:{ confirm: "本当に削除しますか？" } %>
        </th>
          <th><%= user.admin? ? '管理者' : '' %></th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>ユーザー新規作成</h1>
<%= form_with(model: @user, url: admin_users_path(@user),  local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count,"error") %>prohibited this
      <%= @user.name %>from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.radio_button :admin, :true %>
  <%= form.label :admin, "管理者権限を付与する" %>
  <%= form.radio_button :admin, :false %>
  <%= form.label :admin, "権限を削除する" %>

  <%= form.submit "作成" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskExam</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <div class='outer'>
      <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <div class='inner'>
        <% if logged_in? %>
          <%= link_to "My Page", user_path(current_user.id), class: 'btn btn-light btn-lg' %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete, class: 'btn btn-light btn-lg' %>
          <%= link_to 'New Task', new_task_path(@task), class: 'btn btn-light btn-lg' %>
          <%= link_to 'Home', tasks_path, class: 'btn btn-light btn-lg' %>
        <% else %>
          <%= link_to "Sign up", new_user_path, class: 'btn btn-light btn-lg' %>
          <%= link_to "Login", new_session_path, class: 'btn btn-light btn-lg' %>
        <% end %>
        <% if current_user && current_user.admin? %>
          <%= link_to "管理画面", admin_users_path, class: 'btn btn-light btn-lg' %>
        <% end %>
        <%= yield %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります！</h2>
      <ul>
      <%= @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>：
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>：
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.label :expired_at %>：
    <%= form.datetime_field :expired_at %>
  </div>
  <div>
    <%= form.label :status %>：
    <%= form.select :status, Task.statuses.keys, prompt: "ステータスを選択してください" %>
  </div>
  <div>
    <%= form.label :priority %>：
    <%= form.select :priority, Task.priorities.keys %>
  </div>
  <div>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_title) %>
  </div>
  <%= form.submit '送信' %>
<% end %>

app/views/tasks/_search.html.erb
<%= form_with(url: tasks_path, local: true, method: :get) do |form| %>
  <%= form.text_field :search, placeholder: "タイトル" %>
  <%= form.select :status, Task.statuses.keys, prompt: "ステータス" %>
  <%= form.select :label_ids, Label.pluck(:label_title, :id), prompt: "ラベル" %>
  <%= form.submit '検索', class: 'btn btn-outline-dark btn-sm' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集ページ</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<br>
<%= render 'search' %>
<%= link_to '終了期限でソートする', tasks_path(sort_expired: "true"), class: 'btn btn-light' %>
<%= link_to '優先順位でソートする', tasks_path(sort_priority: "true"), class: 'btn btn-light' %>
<br>
<br>
<% if @tasks.any? %>
<table class="table table-bordered border-info">
  <thead>
    <tr>
      <th>ステータス</th>
      <th>優先順位</th>
      <th>タイトル</th>
      <th>内容</th>
      <th>ラベル</th>
      <th>期限</th>
      <th>投稿日</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.labels.map(&:label_title).join(',') %></td>
      <td><%= l task.expired_at, format: :long %></td>
      <td><%= l task.created_at, format: :long %></td>
      <td>
        投稿者：<%= task.user.name %>
        <br>
        <%= link_to '詳細', task_path(task), class: 'btn btn-outline-secondary btn-sm' %>
        <%= link_to '編集', edit_task_path(task), class: 'btn btn-outline-secondary btn-sm' %>
        <%= link_to '削除', task_path(task), class: 'btn btn-outline-secondary btn-sm', method: :delete, data: { confirm: "削除していいですか？"} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>検索結果がありませんでした</p>
<% end %>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>タスク新規投稿ページ</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細ページ</h1>

<p>
  <h4>タスク</h4>
  <%= @task.title %>
</p>
<p>
  <h4>内容</h4>
  <%= @task.content %>
</p>
<p>
  <h4>期限</h4>
  <%= l @task.expired_at, format: :long %>
</p>
<p>
  <h4>ステータス</h4>
  <%= @task.status %>
</p>
<p>
  <h4>優先順位</h4>
  <%= @task.priority %>
</p>
<p>
  <h4>ラベル</h4>
  <%= @task.labels.map(&:label_title).join(',') %>
</p>
<%= link_to '編集', edit_task_path(@task) %>
<%= link_to '削除', task_path(@task), method: :delete, data: { confirm: "削除していいですか？"} %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count,"error") %>prohibited this
      <%= @user.name %>from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "アカウント作成" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のマイページ</h1>
<br>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>投稿者</th>
    </tr>
  </thead>
  <% @user.tasks.each do |user| %>
  <tbody>
    <tr>
      <th><%= user.title %></th>
      <th><%= user.content %></th>
      <th><%= @user.name %></th>
    </tr>
  </tbody>
  <% end %>
</table>